#!/usr/bin/env escript
%% -*- erlang -*-

main(_) ->
    compile:file("tested.erl"),
    {MgsS, SecS, MsS} = erlang:now(),
    
%    tested:eratos_primes(31623),
    tested:main(),

    {MgsE, SecE, MsE} = erlang:now(),
    io:format("~nExecution Time: ~n ~b Sec ~b Msec ~n", [SecE - SecS, 1000000 + MsE - MsS]).
